const lucide = require('lucide-react');
console.log('Phone:', !!lucide.Phone);
console.log('ArrowRight:', !!lucide.ArrowRight);
console.log('ChevronDown:', !!lucide.ChevronDown);
console.log('CheckCircle2:', !!lucide.CheckCircle2);
console.log('ChevronLeft:', !!lucide.ChevronLeft);
console.log('ChevronRight:', !!lucide.ChevronRight);
console.log('Menu:', !!lucide.Menu);
console.log('X:', !!lucide.X);
console.log('Triangle:', !!lucide.Triangle);
console.log('Building:', !!lucide.Building);
console.log('Building2:', !!lucide.Building2);
console.log('Landmark:', !!lucide.Landmark);
console.log('Diamond:', !!lucide.Diamond);
console.log('User:', !!lucide.User);
console.log('Briefcase:', !!lucide.Briefcase);
console.log('Settings:', !!lucide.Settings);
console.log('LinkIcon:', !!lucide.Link);
console.log('Send:', !!lucide.Send);
const framer = require('framer-motion');
console.log('motion:', !!framer.motion);
const countup = require('react-countup');
console.log('CountUp:', !!countup.default);
